//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributes
    {
        public Attributes()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int AttributeID { get; set; }
        public int Subcat_ID { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<double> Wight { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> High { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Describtion { get; set; }
        public bool IsChecked { get; set; }
        public virtual SubCategories SubCategories { get; set; }
        public virtual ICollection<Products> Products { get; set; }

    }
    

}
