//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategories
    {
        public SubCategories()
        {
            this.Attributes = new HashSet<Attributes>();
            this.Products = new HashSet<Products>();
        }
    
        public int SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public int MainCat_ID { get; set; }
        public virtual ICollection<Attributes> Attributes { get; set; }
        public virtual MainCategories MainCategories { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
    public class AttributeItem
    {
        public int AttributeID { get; set; }
        public string AttributeName { get; set; }
        public bool isSelected { get; set; }
    }
}
